### ISSUE TITLE
Build SRO flag

### ISSUE THREAD

**Issue by tpoomlmly** [roboticsoutreach/tasks#54]
## Tasks

- [x] Design the flag
- [x] Buy the flag
- [x] Build the pole + mechanism
- [x] Program the robot

We need to buy a flag if we want one on our bunfight table. [House of Flags](https://www.flags.co.uk) fits our theme of `<product>.co.uk`. Their price is £30/m^2 + VAT, minimum £30.

The SRO logo's aspect ratio is about 16:7

### House of Flags design guidelines

1. The artwork has been placed on the correct template, see the below templates examples. Or alternatively provide a suitable bespoke template
   - [400x250mm](https://www.flags.co.uk/client/uploads/4/400x250mm.pdf)
   - [550x350mm](https://www.flags.co.uk/client/uploads/4/550x350mm.pdf)
   - [750x500mm](https://www.flags.co.uk/client/uploads/4/750x500mm.pdf)
   - [1100x700mm](https://www.flags.co.uk/client/uploads/4/1100x700mm.pdf)
   - [1600x1000mm](https://www.flags.co.uk/client/uploads/4/1600x1000mm.pdf)
2. All important images, text or logos are placed within the ‘safe zone’ of the template
3. The image quality is at 100% and is not pixilated or blurred. We recommend a minimum of 150 DPI (Dots per inch) to ensure your print is not blurred.
4. No crop marks or registration marks have been included in the artwork.
5. The orientation of the artwork is correct and all of the artwork elements are in the correct positions, e.g. logos, texts and images.
6. No notes, descriptions or annotations have been left in the PDF file.
7. All of your artwork is saved in the ‘Your Artwork’ layer and the ‘INFO’ layer has been deleted before sending your finished artwork to us.
8. Your artwork has been provided in one of the following formats:
   - AI (Adobe Illustrator)
   - EPS (Encapsulated PostScript)
   - PDF (Portable Document Format)
   - SVG (Scalable Vector Graphics)
9. No bleed or crop marks

### Hoisting options:

- Eyelets (I think this would be the easiest to control with a motor)
- Rope and toggle (most popular)
- D ring

**Comment by tpoomlmly** [comment]
The flag is ordered

**Comment by tpoomlmly** [comment]
https://github.com/roboticsoutreach/flag
